server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://100.124.10.2:3306/grid?useSSL=false&useUnicode=true&amp&characterEncoding=UTF-8
    username: pdcypro
    password: Sjksh123!@#
#    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&amp&characterEncoding=UTF-8
#    username: root
#    password: haimaroot
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#  mvc:
#    static-path-pattern: /static/**
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.wyc.entity
cbs:
  imagesPath : file:/usr/src/myapp/upload/
#   imagesPath : file:/E:/upload/